name: Mainframe
version: 1.0.0
author: Branel
main: com.branel.dashboard.Mainframe
api-version: 1.16
commands:
  cleanup:
    description: command
    usage: /<command>
  flyspeed:
    description: command
    usage: /speed 0 - 100
  walkspeed:
    description: command
    usage: /speed 0 - 100
  kick:
      description: command
      usage: /speed 0 - 100
  arena:
    description: command
    usage: /speed 0 - 100
  pvpkit:
    description: command
    usage: /speed 0 - 100
  city:
    description: command
    usage: /speed 0 - 100
  gui:
    description: command
    usage: /speed 0 - 100