name: Mainframe
version: 1.0.0
author: Branel
main: com.branel.dashboard.Mainframe
api-version: 1.19
commands:
  cleanup:
    description: command
    usage: /<command>
  flyspeed:
    description: command
    usage: /flyspeed 0 - 100
  walkspeed:
    description: command
    usage: /speed 0 - 100
  kick:
      description: command
      usage: /kick [player]
  arena:
    description: command
    usage: /arena
  pvpkit:
    description: command
    usage: /pvpkit
  city:
    description: command
    usage: /city
  gui:
    description: command
    usage: /gui
  survivalchallenge:
    description: command
    usage: /survivalchallenge