name: Mainframe
version: 1.0.0
author: Branel
main: com.branel.dashboard.Mainframe
api-version: 1.16
commands:
  cleanup:
    description: command
    usage: /<command>
  speed:
    description: command
    usage: /<command>